version: "3.4"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #   - SERVERURL=wireguard.domain.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=10 #optional
      - PEERDNS=auto #optional
    #  - INTERNAL_SUBNET=10.13.13.0 #optional
    #  - ALLOWEDIPS=192.168.1.0/24,192.168.2.0/24 #optional
    volumes:
      - ./vpn-data:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  # openvpn-as:
  #   image: linuxserver/openvpn-as
  #   container_name: openvpn-as
  #   privileged: true
  #   network_mode: host
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - INTERFACE=${INTERFACE} #optional
  #   volumes:
  #     - ./vpn-data:/config
  #   ports:
  #     - 943:943
  #     - 9443:9443
  #     - 1194:1194/udp
  #   restart: unless-stopped
